[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]

[project]
name = "PyDiamond"
version = "1.0.0"
description = "pygame-based game engine"
readme = "README.md"
requires-python = ">=3.10"
authors = [
  {name = "Francis Clairicia-Rose-Claire-Josephine", email = "clairicia.rcj.francis@gmail.com"},
]
license = {file = "LICENSE"}
dependencies = [
    "pygame >=2.1.2",
    "cryptography >=36.0"
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Topic :: Software Development :: Libraries :: pygame",
  "Typing :: Typed"
]

[project.urls]
Source = "https://github.com/francis-clairicia/PyDiamond"

[tool.isort]
profile = "black"
line_length = 130
skip = ["_gradients.py"]
skip_gitignore = true
combine_as_imports = true

[tool.black]
line-length = 130

[tool.mypy]
python_version = "3.10"
warn_unused_configs = true
disallow_any_generics = true
disallow_any_unimported = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_unreachable = true
no_implicit_reexport = true
strict_equality = true
enable_error_code = ["truthy-bool", "ignore-without-code"]

[tool.pytest.ini_options]
minversion = "6.2.5"
addopts = "-ra -v"
testpaths = ["tests"]
